### ISSUE TITLE
Just a Word (not an issue) about this amazing repo!

### ISSUE THREAD

**Issue by loneicewolf** [bgstaal/multipleWindow3dScene#1]
First things first - **thanks** for making this!

I just checked it out:
- https://bgstaal.github.io/multipleWindow3dScene/ 

And it's just amazing, I have to make a issue saying this (really this is everything I wanted to convey)
Have a great day and, Respect for making This Repo.

</sub>

Wishes from Sweden!
Will.

</sub>

**Comment by loneicewolf** [comment]
Oh By the way this can be closed, it's just a appreciation post really ^_^ 
good lucks from sweden! ❤️

**Comment by ajf1016** [comment]
✨

**Comment by ok-coder1** [comment]
@loneicewolf You should close this as I don't think anybody has the write permissions.
