### ISSUE TITLE
Cors Policy

### ISSUE THREAD

**Issue by FaizaanFazal** [bgstaal/multipleWindow3dScene#28]
How to solve this :
Access to script at 'file:///D:/user/Threejs/multipleWindow3dScene-main/main.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome, https, chrome-untrusted.

**Comment by ok-coder1** [comment]
Use the website created by the creator himself: https://bgstaal.github.io/multipleWindow3dScene/

**Comment by FaizaanFazal** [comment]
I just installed three.js using npm and cors policy issue went away.

**Comment by devFortes** [comment]
use 
cd C:\Program Files\Google\Chrome\Application
chrome.exe  --disable-site-isolation-trials --disable-web-security --user-data-dir="local-your-path"
