### ISSUE TITLE
Can you make this online?

### ISSUE THREAD

**Issue by pousay** [bgstaal/multipleWindow3dScene#40]
Please make this online using gh-pages
And put the link in readme file or description♥️

**Comment by Matheus-gs** [comment]
Hi @pousay this is already published on GH pages, you can access here:
[https://bgstaal.github.io/multipleWindow3dScene/](https://bgstaal.github.io/multipleWindow3dScene/)

**Comment by Lobohombo** [comment]
Soy de México y también de la tercera edad me mandaría sus mensajes en mi
idioma

Único dueñoDarioRodolfo

**Comment by pousay** [comment]
https://bgstaal.github.io/multipleWindow3dScene/

**Comment by pousay** [comment]
https://bgstaal.github.io/multipleWindow3dScene/
