### ISSUE TITLE
didnt work

### ISSUE THREAD

**Issue by DgithubA** [bgstaal/multipleWindow3dScene#41]
script didnt work in local.
![image](https://github.com/bgstaal/multipleWindow3dScene/assets/56259646/a4227644-06cb-4179-ac6f-d656dac099f3)

**Comment by yaroslavlopush** [comment]
![1move](https://github.com/bgstaal/multipleWindow3dScene/assets/2319233/8803785a-c3a5-4103-adf9-9ff53826dc51)
![2move](https://github.com/bgstaal/multipleWindow3dScene/assets/2319233/aa5f6104-3562-47d7-b463-29ae21d2bc8a)
![3move](https://github.com/bgstaal/multipleWindow3dScene/assets/2319233/4cd34d44-8ed2-444e-97d6-202930794bdf)

**Comment by yaroslavlopush** [comment]
And it will work locale :)

**Comment by yaroslavlopush** [comment]
Or use this: https://bgstaal.github.io/multipleWindow3dScene/

**Comment by Lobohombo** [comment]
De favor en mi idioma soy de México

Único dueñoDarioRodolfo
